### ISSUE TITLE
arm64 rb5009 yaffs will not read

### ISSUE THREAD

**Issue by john-tho** [kempniu/yafut#5]
Another low/no priority ticket expanding use.

The RouterOS command line includes: `yaffs.inband_tags=1`. It also includes the RouterOS specific `nand_base.c` params: `benand_no_swecc=2 mlc=11`: https://github.com/john-tho/linux/blob/708fc99a000d4a7fef9fa0e19caf857f2634caf0/drivers/mtd/nand/raw/nand_base.c#L167, but I don't think they matter here.

```
root@OpenWrt:/# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00800000 00020000 "RouterBoard NAND Boot"
mtd1: 3f800000 00020000 "RouterBoard NAND Main"
mtd2: 00400000 00001000 "RouterBoot"
mtd3: 00001000 00001000 "hard_config"
mtd4: 00001000 00001000 "soft_config"
mtd5: 00005a8f 00001000 "dtb_config"
root@OpenWrt:/# yafut -d /dev/mtd0 -r -i kernel -o /tmp/kernel -v
mtd.c:359: init_yaffs_dev: /dev/mtd0: type=04, flags=00000400, size=00800000, erasesize=00020000, writesize=00000800, oobsize=00000040
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=0, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=64, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=128, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=192, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=256, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=320, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=384, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=448, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=512, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=576, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=640, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=704, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=768, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=832, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=896, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=960, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1024, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1088, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1152, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1216, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1280, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1344, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1408, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1472, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1536, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1600, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1664, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1728, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1792, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1856, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1920, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1984, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2048, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2112, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2176, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2240, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2304, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2368, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2432, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2496, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2560, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2624, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2688, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2752, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2816, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2880, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2944, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3008, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3072, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3136, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3200, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3264, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3328, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3392, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3456, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3520, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3584, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3648, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3712, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3776, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3840, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3904, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3968, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=4032, data=0 (2048), oob=0x7fe406f9b0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=0, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=0, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=1, ret=1, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=64, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=2, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=128, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=3, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=192, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=4, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=256, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=5, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=320, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=6, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=384, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=7, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=448, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=8, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=512, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=9, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=576, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=10, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=640, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=11, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=704, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=12, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=768, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=13, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=832, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=14, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=896, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=15, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=960, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=16, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1024, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=17, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1088, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=18, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1152, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=19, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1216, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=20, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1280, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=21, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1344, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=22, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1408, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=23, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1472, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=24, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1536, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=25, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1600, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=26, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1664, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=27, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1728, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=28, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1792, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=29, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1856, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=30, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1920, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=31, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=1984, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=32, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2048, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=33, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2112, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=34, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2176, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=35, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2240, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=36, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2304, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=37, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2368, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=38, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2432, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=39, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2496, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=40, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2560, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=41, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2624, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=42, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2688, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=43, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2752, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=44, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2816, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=45, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2880, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=46, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2944, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=47, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3008, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=48, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3072, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=49, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3136, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=50, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3200, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=51, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3264, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=52, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3328, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=53, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3392, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=54, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3456, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=55, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3520, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=56, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3584, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=57, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3648, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=58, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3712, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=59, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3776, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=60, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3840, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=61, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3904, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=62, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=3968, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:139: mtd_check_bad: /dev/mtd0: ioctl=MEMGETBADBLOCK, block=63, ret=0, err=0 (No error information)
mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=4032, data=0 (2048), oob=0x7fe406f9d0 (28), ret=0, err=0 (No error information)
mtd.c:502: mtd_mount: /dev/mtd0: successfully mounted Yaffs filesystem
mtd.c:537: mtd_file_open: /dev/mtd0: yaffs_open, path=kernel, ret=-1
mtd.c:541: mtd_file_open: /dev/mtd0: yaffs_open, err=-2
copy.c:182: read_file_from_mtd: unable to open file on MTD for reading: error -2 (No such file or directory)
copy.c:275: copy_file: copying failed: error -2 (No such file or directory)
mtd.c:516: mtd_unmount: /dev/mtd0: unmounting Yaffs filesystem
mtd.c:326: mtd_write_chunk: /dev/mtd0: ioctl=MEMWRITE, chunk=0, data=0x7f9e342070 (2048), oob=0x7fe406fbb0 (28), ret=-1, err=-1 (Operation not permitted)
```

Looking at the OEM (RouterOS) support file dump: `grep -r --binary-files=text yaffs . | sort -u`
```
./03_.startup:		 23.15@3: [    0.000000] Kernel command line: root=/dev/ram0 no-uart no-buzzer benand_no_swecc=2 yaffs.inband_tags=1 parts=1 boot_part_size=8388608 arm64=Y board=5009 ver=7.0.5 bver=7.0.5 hw_opt=00180005 boot=1 mlc=11
./03_.startup:		 23.15@3: [    0.036743] yaffs: yaffs Installing.
./03_.startup:		 23.15@3: [   19.776381] yaffs: dev is 32505857 name is "mtdblock1" rw
./03_.startup:		 23.15@3: [   19.776384] yaffs: passed flags ""
./03_.startup:		 23.15@3: [   19.776387] yaffs: yaffs: Attempting MTD mount of 31.1,"mtdblock1"
./03_.startup:		 23.15@3: [   19.776390] yaffs: auto selecting yaffs2
./03_.startup:		 23.15@3: [   19.860482] yaffs: yaffs_read_super: is_checkpointed 1
./03_.startup:		 23.15@3: [   19.863142] yaffs: dev is 32505856 name is "mtdblock0" rw
./03_.startup:		 23.15@3: [   19.863145] yaffs: passed flags ""
./03_.startup:		 23.15@3: [   19.863147] yaffs: yaffs: Attempting MTD mount of 31.0,"mtdblock0"
./03_.startup:		 23.15@3: [   19.863149] yaffs: auto selecting yaffs2
./03_.startup:		 23.15@3: [   19.875440] yaffs: yaffs_read_super: is_checkpointed 1
```

The u-boot YAFFS driver does work with this partition:
```
=> ydevconfig booter nand 0 40
=> ymount booter
=> yls -l booter
kernel                   	2550144   769 regular file
VERSION                  	     38   513 regular file
rw                       	   2032   258 directory
lost+found               	   2032     2 directory
=> yrdm booter/kernel ${loadaddr} 
Copy booter/kernel to 0x0000000000800000... 	[DONE]
```
https://source.denx.de/u-boot/u-boot/-/blob/master/fs/yaffs2/yaffs_uboot_glue.c#L233:
```
	if (chip->ecc.layout->oobavail < sizeof(struct yaffs_packed_tags2))
		dev->param.inband_tags = 1;
```

**Comment by kempniu** [comment]
Could you please test the `force-inband-tags` branch that I have just pushed?  It is a quick-and-dirty one-line change (1240f837c88318058c57f33b3a4ae6c5f8798a44) on top of `main`:

```diff
diff --git a/src/mtd.c b/src/mtd.c
index 2695a52..16cb0a0 100644
--- a/src/mtd.c
+++ b/src/mtd.c
@@ -376,6 +376,7 @@ static int init_yaffs_dev(struct mtd_ctx *ctx) {
 			.end_block = (mtd->size / mtd->erasesize) - 1,
 			.n_reserved_blocks = 2,
 			.is_yaffs2 = (mtd->writesize >= 2048 ? 1 : 0),
+			.inband_tags = 1,
 		},
 		.drv = yaffs_driver_mtd,
 		.driver_context = ctx,
```

If this turns out to be enough to enable Yafut to read files on that device, I will implement the same heuristics as U-Boot does - they seem reasonable to me for auto-detecting use of inband tags in the general case.  However, I would rather wait until you get back to me with testing results before jumping on this because Yafut will need to get the number of OOB bytes available for use from sysfs as the `oobavail` field is not present in the `struct mtd_info_user` [structure](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/mtd/mtd-abi.h?h=v6.2&id=c9c3395d5e3dcc6daee66c6908354d47bf98cb0c#n175) returned by the MEMGETINFO ioctl - and that's a bit more work than the one-line hack above.

**Comment by john-tho** [comment]
No rush on this. Still do not have a good (OpenWrt upstreamable) way of booting this device with our DTS. 

Yes, `force-inband-tags` allows me to read files as expected, and the `kernel` `sha256sum` matched that extracted with u-boot's `yrdm`

Writing a file back does not error, but does not work as expected. After the original file is re-written, a new read of the same file gives different bytes following each write.
```
[  728.149695] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
```
logs here: https://gist.github.com/john-tho/e5d6cc74f060a2b22efa5897c8d8290a

```
for fn in $(find /sys/class/mtd/mtd0/ -maxdepth 1 -type f); do p
rintf "%s:\n%s\n" $(basename $fn) $(cat $fn); done
uevent:
MAJOR=90
MINOR=0:
DEVNAME=mtd0
DEVTYPE=mtd:
OF_NAME=partition
OF_FULLNAME=/cp0/config-space@f2000000/nand@720000/nand@0/partitions/partition@0:
OF_COMPATIBLE_N=0
erasesize_minor:
0
writesize:
2048
bitflip_threshold:
12
oobsize:
64
corrected_bits:
87
oobavail:
30
ecc_failures:
0
erasesize:
131072
dev:
90:0
ecc_step_size:
2048
bbt_blocks:
0
type:
nand
offset:
0
subpagesize:
2048
ecc_strength:
16
bad_blocks:
5
size:
8388608
numeraseregions:
0
name:
RouterBoard
NAND:
Boot
flags
```

**Comment by kempniu** [comment]
Thank you for providing the debug logs.

AFAICT, there are two issues at play here:

  1. file system inconsistencies,
  2. a Yafut bug that I have a fix for.

Here is what I believe happens while writing to `/dev/mtd0`:

  - Yaffs code loads a checkpoint block, from which it reads the current state of all blocks

    ```
    yaffs: yaffs: yaffs_ll_init()
    yaffs: restore entry: is_checkpointed 0
    yaffs: read checkpoint validity 
    ...
    yaffs: Block summary
    yaffs: 0 blocks have illegal states
    yaffs: Unknown 0 blocks
    yaffs: Scanning 0 blocks
    yaffs: Needs scan 0 blocks
    yaffs: Empty 24 blocks
    yaffs: Allocating 1 blocks
    yaffs: Full 38 blocks
    yaffs: Dirty 0 blocks
    yaffs: Checkpoint 1 blocks
    yaffs: Collecting 0 blocks
    yaffs: Dead 0 blocks
    yaffs: restore exit: is_checkpointed 1
    ...
    yaffs: yaffs: restored from checkpoint
    ```

    According to the above, 24 blocks on `/dev/mtd0` should be empty.

  - Yaffs code starts writing data chunks to the block from which it's currently allocating and keeps on going through available blocks for a while:

    ```
    mtd.c:326: mtd_write_chunk: /dev/mtd0: ioctl=MEMWRITE, chunk=2686, data=0x7fa40c6030 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ...
    mtd.c:326: mtd_write_chunk: /dev/mtd0: ioctl=MEMWRITE, chunk=2687, data=0x7fa40c6ad0 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ...
    yaffs: Allocated block 3, seq  4140, 23 left
    ...
    mtd.c:326: mtd_write_chunk: /dev/mtd0: ioctl=MEMWRITE, chunk=128, data=0x7fa40c6030 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ```

  - At some point, it hits a block that it believes should be empty, but isn't - and the problem happens for all remaining blocks that were marked as empty in the checkpoint data (Yaffs code only checks the first chunk in each block and then skips the rest of the block if the erasure check fails):

    ```
    yaffs: Allocated block 43, seq  4142, 21 left
    yaffs: yaffs_tags_marshall_read chunk 2688 data 0x7fa40c6ad0 tags 0x7ffc481008
    mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2688, data=0x7fa40c6ad0 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ...
    yaffs: Chunk 2752 not erased
    yaffs: **>> yaffs chunk 2752 was not erased
    yaffs: line 549 delete of chunk 2752
    yaffs: Allocated block 44, seq  4143, 20 left
    yaffs: yaffs_tags_marshall_read chunk 2752 data 0x7fa40c6ad0 tags 0x7ffc481008
    mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2752, data=0x7fa40c6ad0 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ...
    yaffs: Chunk 2816 not erased
    yaffs: **>> yaffs chunk 2816 was not erased
    yaffs: line 549 delete of chunk 2816
    yaffs: Allocated block 45, seq  4144, 19 left
    yaffs: yaffs_tags_marshall_read chunk 2816 data 0x7fa40c6ad0 tags 0x7ffc481008
    mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=2816, data=0x7fa40c6ad0 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ...
    yaffs: Chunk 2880 not erased
    yaffs: **>> yaffs chunk 2880 was not erased
    ```

  - Since Yaffs code marks blocks that should have been erased but seemingly weren't as full, the Yaffs allocator soon runs out of usable blocks to write data chunks to:

    ```
    mtd.c:275: mtd_read_chunk: /dev/mtd0: ioctl=MEMREAD, chunk=4032, data=0x7fa40c6ad0 (2048), oob=0 (0), ret=0, err=0 (No error information)
    ...
    yaffs: Chunk 4096 not erased
    yaffs: **>> yaffs chunk 4096 was not erased
    yaffs: line 549 delete of chunk 4096
    yaffs: yaffs tragedy: no more erased blocks
    yaffs: Allocating reserve
    yaffs: !!!!!!!!! Allocator out !!!!!!!!!!!!!!!!!
    yaffs: **>> yaffs write required 22 attempts
    mtd.c:645: mtd_file_write: /dev/mtd0: yaffs_write, fd=0, ret=672
    ```

  - Since `yaffs_write()` successfully wrote a *part* of the input file to the MTD, it correctly returns a positive integer (672).  This is where Yafut errs: a short write happened (672 < 2048), but `copy_from_file_to_mtd()` treats this as a successful write and simply moves on to reading the next 2048 bytes from the input file.  What it should have done instead is retry the write operation using correct offsets (and potentially keep on retrying until the whole chunk it read from the input file gets written to the MTD).  You can tell from the rest of the log file that Yaffs code is able to reclaim unused blocks for the subsequent `yaffs_write()` calls.  That is why `yafut` returns with an exit code of 0, which falsely suggests it succeeded.

Could you please retest with the current version of the `force-inband-tags` branch (currently at 41425276767b877c6ad5a3af542e75e917432916)?

If writing still fails, could you please provide write logs like the ones you provided above, but for **two** consecutive `yafut` invocations using the `-w` switch?

**Comment by john-tho** [comment]
Thank you for digging into that.
With https://github.com/kempniu/yafut/commit/41425276767b877c6ad5a3af542e75e917432916, getting the same outcome for writes.
Some writes result in the same output `sha256sum`, but it does not match the input.
Log truncated to: write, write, read here: https://gist.github.com/john-tho/e5d6cc74f060a2b22efa5897c8d8290a#file-log-414252
Full log of all my writes & read here: [log-414252.zip](https://github.com/kempniu/yafut/files/11082161/log-414252.zip). I did write the wrong input file the first time.

Cheers

**Comment by kempniu** [comment]
Thanks for testing.  Before I take a closer look at the debug logs you provided, I need to double-check your collection method because I found something troubling:

  - on line 93152 of the unpacked `log-414252` file, the following `yafut` invocation is shown:

        YAFFS_TRACE_MASK=0xffffffff yafut -v -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel2

  - the next `yafut` invocation only starts on line 175525

  - meanwhile, line 137653 shows this ioctl:

        mtd.c:326: mtd_write_chunk: /dev/mtd0: ioctl=MEMWRITE, chunk=2641, data=0x7f9e45a030 (2048), oob=0 (0), ret=0, err=0 (No error information)

Collectively, these lines suggest that `yafut` invoked with the `-r` (**read**) switch caused a **write** that was allowed by the kernel.  I do not see how this could have happened, given that `-r` [causes](https://github.com/kempniu/yafut/blob/41425276767b877c6ad5a3af542e75e917432916/src/mtd.c#L407) the MTD character device to be opened in read-only mode, which in turn should cause the kernel to [immediately refuse](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/mtd/mtdchar.c?h=v6.2&id=c9c3395d5e3dcc6daee66c6908354d47bf98cb0c#n870) any ioctls that might cause writes.  (Note that the output in the OP was also captured for a `yafut -r ...` invocation and it contains the expected `Operation not permitted` response to a MEMWRITE attempt.)

I apologize if it feels like I am being picky, I am merely trying to prevent GIGO.

Looking at this from another angle, could you perhaps provide me with a `nanddump` of `/dev/mtd0`?  Something like this should do:

    nanddump --bb=dumpbad --noecc --oob --file=mtd0.bin

Also, the output of `dmesg | grep -i nand` would be useful.

**Comment by john-tho** [comment]
> lines suggest that `yafut` invoked with the `-r` (**read**) switch caused a **write**

Sorry. Very likely that I forgot to do an `echo YAFFS_TRACE_MASK=0xffffffff yafut -v -d /dev/mtd0 -w -o kernel -i /tmp/yaffs-kernel 2>&1 | tee -a log-414252` before running the command. (Mis)using up arrow for command history.

dmesg:
```
[    0.037731] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.759157] nand: device found, Manufacturer ID: 0xc2, Chip ID: 0xd3
[    0.765557] nand: Macronix MX60LF8G18AC
[    0.769408] nand: 1024 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.790720] nand_read_bbt: bad block at 0x000000020000
[    0.795897] nand_read_bbt: bad block at 0x000004c60000
[    0.801063] nand_read_bbt: bad block at 0x0000147e0000
[    0.806229] nand_read_bbt: bad block at 0x00001ce20000
[    0.811389] nand_read_bbt: bad block at 0x000020080000
[    0.816552] nand_read_bbt: bad block at 0x000024340000
[    0.821711] nand_read_bbt: bad block at 0x000026280000
[    0.826873] nand_read_bbt: bad block at 0x0000289a0000
[    0.832033] nand_read_bbt: bad block at 0x00002c980000
[    0.837195] nand_read_bbt: bad block at 0x00002ce60000
[    0.845923] 2 fixed-partitions partitions found on MTD device f2720000.nand
[    0.852918] Creating 2 MTD partitions on "f2720000.nand":
[    0.858348] 0x000000000000-0x000000800000 : "RouterBoard NAND Boot"
[    0.864880] 0x000000800000-0x000040000000 : "RouterBoard NAND Main"
[  728.149695] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[  861.198883] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[  921.046904] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[ 1037.052465] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36121.586957] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36233.099216] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36377.189610] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36384.246480] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36487.659654] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36554.366471] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[36564.010530] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
[37676.869527] nand: nand_erase_nand: attempt to erase a bad block at page 0x00000040
```
nanddump: 
[rb5009-yafut-mtd0.bin.zip](https://github.com/kempniu/yafut/files/11083842/rb5009-yafut-mtd0.bin.zip)

Cheers

**Comment by kempniu** [comment]
Argh!!! Time for quite an egg-on-face moment.  It turns out that `mtd_check_bad()`, the Yafut function that Yaffs code uses to determine whether a given block is bad, incorrectly reports bad blocks as good :roll_eyes:

The `dmesg` output and the `nanddump` you posted above were both crucial in getting down to the bottom of this, thanks.  The `attempt to erase a bad block` message you posted [earlier](#issuecomment-1484801971) also should have been a hint, but things are always so clear in hindsight...

Anyway, here is what I believe kept happening.  Your `/dev/mtd0` contains a **stale** Yaffs checkpoint in block 1, which is a bad block.  Since Yaffs code was unaware that this is a bad block (because of the Yafut bug I mentioned above), it processed that checkpoint and assumed it reflects the current file system state.  That's why it got confused later on about pages that should have been erased, but weren't.  Since the kernel prevents erasing bad blocks, the stale Yaffs checkpoint continued to live there.  That's why, even though Yafut wrote an updated checkpoint to the MTD during unmounting after each write attempt, every subsequent Yafut invocation still resulted in Yaffs code loading the stale checkpoint from the bad block.  Nothing here could have worked as expected.

Could you please retest with the current version of the `force-inband-tags` branch (currently at 454113da8447f8a659c27b20e3b2cf96d34da101)?

If writing still fails, could you please provide me with a correct copy of the `kernel` file that you are able to boot the device with and debug logs from two Yafut invocations attempting to write that file back to `/dev/mtd0`?

**Comment by john-tho** [comment]
> Argh!!!

Not at all. Great bug hunting.

> Could you please retest with the current version of the `force-inband-tags` branch (currently at [454113d](https://github.com/kempniu/yafut/commit/454113da8447f8a659c27b20e3b2cf96d34da101))?

Good write, and good read:

```bash
BusyBox v1.36.0 (2023-03-22 00:07:38 UTC) built-in shell (ash)

root@OpenWrt:~# opkg install yafut_2023-03-28-454113da-1_aarch64_cortex-a72.ipk
Upgrading yafut on root from 2023-03-27-41425276-1 to 2023-03-28-454113da-1...
Configuring yafut.
root@OpenWrt:~# opkg list-installed | grep yafut
yafut - 2023-03-28-454113da-1
root@OpenWrt:~# sha256sum /tmp/yaffs-kernel*
e044815173e33a64fd373736c3a4ee96c024a2a8281776a6313d2d5385019994  /tmp/yaffs-ker
nel
0f4321a635e2ac391bb1562e1e2e44e6bc98285ecafbb1ebd80ab117a51ba5da  /tmp/yaffs-ker
nel2
root@OpenWrt:~# yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel2
root@OpenWrt:~# echo $?
0
root@OpenWrt:~# sha256sum /tmp/yaffs-kernel*
e044815173e33a64fd373736c3a4ee96c024a2a8281776a6313d2d5385019994  /tmp/yaffs-ker
nel
e448e9cf24ae0294f1d444408a2ae951db8169634b9910ed0762e11eece67d7a  /tmp/yaffs-ker
nel2
root@OpenWrt:~# yafut -d /dev/mtd0 -w -o kernel -i /tmp/yaffs-kernel
root@OpenWrt:~# dmesg | tail
[95368.556504] br-wan: port 2(p1) entered disabled state
[95368.561718] mv88e6085 f212a200.mdio-mii:00 p1: Link is Down
[95370.891114] mv88e6085 f212a200.mdio-mii:00 p1: Link is Up - 10Mbps/Full - flo
w control rx/tx
[95370.899704] br-wan: port 2(p1) entered blocking state
[95370.904816] br-wan: port 2(p1) entered forwarding state
[123761.276422] br-wan: port 2(p1) entered disabled state
[123761.282206] mv88e6085 f212a200.mdio-mii:00 p1: Link is Down
[123764.981142] mv88e6085 f212a200.mdio-mii:00 p1: Link is Up - 1Gbps/Full - flo
w control rx/tx
[123764.989708] br-wan: port 2(p1) entered blocking state
[123764.994892] br-wan: port 2(p1) entered forwarding state
root@OpenWrt:~# yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel2
root@OpenWrt:~# sha256sum /tmp/yaffs-kernel*
e044815173e33a64fd373736c3a4ee96c024a2a8281776a6313d2d5385019994  /tmp/yaffs-ker
nel
e044815173e33a64fd373736c3a4ee96c024a2a8281776a6313d2d5385019994  /tmp/yaffs-ker
nel2
root@OpenWrt:~# yafut -d /dev/mtd0 -w -o kernel -i /tmp/yaffs-kernel
root@OpenWrt:~# echo $?
0
root@OpenWrt:~# yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel2
root@OpenWrt:~# echo $?
0
root@OpenWrt:~# sha256sum /tmp/yaffs-kernel*
e044815173e33a64fd373736c3a4ee96c024a2a8281776a6313d2d5385019994  /tmp/yaffs-ker
nel
e044815173e33a64fd373736c3a4ee96c024a2a8281776a6313d2d5385019994  /tmp/yaffs-ker
nel2
root@OpenWrt:~# exit

root@OpenWrt:~# /tmp/nand-utils/usr/sbin/nanddump --bb=dumpbad --noecc --oob --f
ile=/tmp/mtd0-yafut.bin /dev/mtd0
Block size 131072, page size 2048, OOB size 64
Dumping data starting at 0x00000000 and ending at 0x00800000...
root@OpenWrt:~# hexdump -C -n $((0x1000*2)) /tmp/mtd0-yafut.bin
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000007f0  b1 b8 ca a9 01 03 00 00  0d 00 00 00 c0 00 00 00  |................|
00000800  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00000820  c3 67 b3 52 bd 0b 99 21  7b 0d a4 18 6a d3 d6 59  |.g.R...!{...j..Y|
00000830  23 c6 6f 1d 1c 0b 78 c9  e9 03 33 78 48 d7 ff ff  |#.o...x...3xH...|
00000840  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001030  b1 b8 ca a9 01 03 00 00  0d 00 00 00 f0 07 00 00  |................|
00001040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00001060  3c c6 c4 38 6f 88 00 22  79 ff d9 93 84 41 6d d1  |<..8o.."y....Am.|
00001070  f3 aa 50 a7 17 6c 14 07  a1 63 56 3f 99 1e ff ff  |..P..l...cV?....|
00001080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001870  b1 b8 ca a9 01 03 00 00  0e 00 00 00 d0 00 00 00  |................|
00001880  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
000018a0  0d 2a 10 0e 39 b2 72 92  ab 1f 1b da fd 00 6c 75  |.*..9.r.......lu|
000018b0  1a 36 3f ca 1f 00 2a 51  c0 19 dc 88 1c f6 ff ff  |.6?...*Q........|
000018c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00002000
root@OpenWrt:~# grep -n kernel /tmp/mtd0-yafut.bin
1429430:kernel
1446737:kernel
1447047:kernel
root@OpenWrt:~# hexdump -C /tmp/mtd0-yafut.bin  | grep kernel
0052f380  01 00 00 00 01 00 00 00  ff ff 6b 65 72 6e 65 6c  |..........kernel|
00664980  01 00 00 00 01 00 00 00  ff ff 6b 65 72 6e 65 6c  |..........kernel|
006651c0  01 00 00 00 01 00 00 00  ff ff 6b 65 72 6e 65 6c  |..........kernel|
root@OpenWrt:~# exit

```

**Comment by kempniu** [comment]
Cool, thanks, this looks sane to me.

I have now prepared a proper branch that automatically detects whether inband tags should be expected, see #9.  Could you please perform one more read/write test using that branch before I merge it?

**Comment by john-tho** [comment]
Sorry, looks like I may have lead you on a bit of a bum steer.
With the [auto-inband-tags](https://github.com/kempniu/yafut/tree/inband-tags-autodetection) branch, inband tags are not activated, because tags would fit in `mtd_info->oobavail`, and `yafut` read fails. I should have picked this up when I saw my `oobavail` sysfs number.
With some extra debug prints:
```
mtd.c:434: init_yaffs_dev: /dev/mtd0: is_yaffs2=1 && oobavail=30 <? sizeof(struct yaffs_packed_tags2)=28 == 0
```

In u-boot, the oobavail of the ECC layout is tested against: `struct nand_chip->struct nand_ecc_ctrl.`[`struct nand_ecclayout`](https://elixir.bootlin.com/u-boot/latest/C/ident/nand_ecclayout)`->oobavail`. Guessing this is the obsolete [`struct nand_ecclayout_user`](https://elixir.bootlin.com/linux/latest/C/ident/nand_ecclayout_user) in Linux.

With an extra debug prints:
```
=> mtd list
List of MTD devices:
* nand0
  - device: nand@720000
  - parent: config-space
  - driver: pxa3xx-nand
  - path: /cp0/config-space/nand@720000
  - type: NAND flash
  - block size: 0x20000 bytes
  - min I/O: 0x800 bytes
  - OOB size: 64 bytes
  - OOB available: 30 bytes
  - ECC strength: 16 bits
  - ECC step size: 2048 bytes
  - bitflip threshold: 12 bits
  - 0x000000000000-0x000040000000 : "nand0"
          - 0x000000000000-0x000000800000 : "RouterBoard NAND Boot"
          - 0x000000800000-0x000040000000 : "RouterBoard NAND Main"

=> ydevconfig booter nand0 0 0x40
yaffs mount booter: dev 0 chip->ecc.layout->oobavail: 0 sizeof(struct yaffs_packed_tags2):28 (chip->ecc.layout->oobavail <  sizeof(struct yaffs_packed_tags2)): 1
Configures yaffs mount booter: dev 0 start block 0, end block 64 using inband tags
=> ymount booter
Mounting yaffs2 mount point booter
=> yls -l booter
rw                                 2032   258 directory
nova                               2032   259 directory
var                                2032   261 directory
image                            109728   263 regular file
kernel                          2768872   257 regular file
lost+found                         2032     2 directory
```

With `inband_tags = 1` forced atop the auto-inband tags branch, `yafut` read works fine.
I can try to look through RouterBOOT to see what it is testing to set inband_tags.

Sorry… at least we fixed some bugs along the way.
I will keep digging.

**Comment by kempniu** [comment]
> Sorry, looks like I may have lead you on a bit of a bum steer. With the [auto-inband-tags](https://github.com/kempniu/yafut/tree/inband-tags-autodetection) branch, inband tags are not activated, because tags would fit in `mtd_info->oobavail`, and `yafut` read fails. I should have picked this up when I saw my `oobavail` sysfs number.

Ah, of course!  I should have noticed that as well :-)

> In u-boot, the oobavail of the ECC layout is tested against: `struct nand_chip->struct nand_ecc_ctrl.`[`struct nand_ecclayout`](https://elixir.bootlin.com/u-boot/latest/C/ident/nand_ecclayout)`->oobavail`. Guessing this is the obsolete [`struct nand_ecclayout_user`](https://elixir.bootlin.com/linux/latest/C/ident/nand_ecclayout_user) in Linux.

I looked into this a bit further and it seems to me that the U-Boot Yaffs driver might have "worked" with this device by pure coincidence.  The U-Boot version of the `pxa3xx-nand` NAND driver has recently had its OOB layout information ripped out from externally-accessible structures:

https://github.com/u-boot/u-boot/commit/1ba0018218e141d444d75e9a59e397704292fe68

Note that the `pxa3xx-nand` driver does not even exist in the Linux kernel any more as it has been superseded by the `marvell-nfc` driver back in 2018:

https://github.com/torvalds/linux/commit/cc396436c24de8ae28b3c0bee795a19bffea815b

However, before it was removed, it did expose OOB layout information to userspace, and so did the U-Boot version before u-boot/u-boot@1ba0018218e141d444d75e9a59e397704292fe68.

> With `inband_tags = 1` forced atop the auto-inband tags branch, `yafut` read works fine. I can try to look through RouterBOOT to see what it is testing to set inband_tags.

The thing is, even if you manage to figure that out, it will very likely be non-actionable information from Yafut's perspective.  Yafut does not have low-level HW access and even if it did, wiring device-specific heuristics into it feels wrong.  If anything, the problem could instead be solved by enabling some sort of a call-out to an external executable that would determine whether inband tags should be used for a specific device.

However, the simplest course of action for now seems to be to enable forcing inband tags via a command-line option.

At any rate, the `inband-tags-autodetection` branch is going to be useful anyway as inband tags **must** be used when there is **not** enough available space in the OOB area to store them.  However, inband tags **can** also be used if there **is** enough space in the OOB area to store them (which is what we're dealing with in this particular case) - and this is the part that's impossible to autodetect by definition.  I was just hoping that maybe the heuristics checking available OOB bytes will be good enough in practice.  Oh well.  I'll just tweak the commit messages and remove the "Fixes #5" part from cd58c39c0b8f90fdccbed8b1380af8b65971349c.

I will also prepare another branch that enables forcing use of inband tags.

**Comment by john-tho** [comment]
Yes, all sounds fair.

Yes, a cli parameter to force inband tags sounds like the best approach for now.

Cheers

**Comment by kempniu** [comment]
Could you please give b97d143ded3eea89d53bc03f6366469eb433a372 a shot?

`yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel-inband-tags` should **not** work with this device.

`yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel-inband-tags -T` should work, though.

**Comment by john-tho** [comment]
> Could you please give [b97d143](https://github.com/kempniu/yafut/commit/b97d143ded3eea89d53bc03f6366469eb433a372) a shot?
> 
> `yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel-inband-tags` should **not** work with this device.
> 
> `yafut -d /dev/mtd0 -r -i kernel -o /tmp/yaffs-kernel-inband-tags -T` should work, though.

Worked as expected:
would not read without `-T`
did read with `-T`, and the written file matches when re-read
RouterBOOT did boot the u-boot ELF I used `yafut` to write to kernel

Cheers
